Add gtag.js 📈
YouClap/youclap.github.io pull request #11
Opened 2018-12-18 17:16 UTC by reinaldo89

2018-12-18 18:22 UTC, ruimartinsptl approved these changes

2018-12-18 18:22 UTC, ruimartinsptl approved these changes

2018-12-18 18:23 UTC, ruimartinsptl approved these changes

2018-12-18 20:28 UTC, portellaa requested changes
Instead of have the same code duplicated through all the files, create a JS file with it 🙂

2018-12-18 20:28 UTC, portellaa commented on contact.html
> +        window.dataLayer = window.dataLayer || [];
please move this to a ga.js file instead of duplicate the same code through all the files 🙂

2018-12-20 14:11 UTC, portellaa approved these changes

2018-12-20 15:35 UTC, merged